from __future__ import annotations

import importlib
import os
import sys

import pytest


def _reload_db(monkeypatch, tmp_path, *, database_url: str | None = None):
    for name in list(sys.modules):
        if name == "db" or name.startswith("clipforge_v3"):
            sys.modules.pop(name, None)
    monkeypatch.delenv("DB_URL", raising=False)
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "data"))
    monkeypatch.setenv("DB_PATH", str(tmp_path / "data" / "clipforge.db"))
    if database_url is None:
        monkeypatch.delenv("DATABASE_URL", raising=False)
    else:
        monkeypatch.setenv("DATABASE_URL", database_url)
    return importlib.import_module("db")


def test_default_database_url_uses_local_sqlite(monkeypatch, tmp_path):
    db = _reload_db(monkeypatch, tmp_path)

    assert db.database_dialect() == "sqlite"
    db.init_db()

    row = db.fetch_one("SELECT COUNT(*) AS count FROM jobs")
    assert row["count"] == 0


def test_legacy_sqlite_db_url_remains_supported(monkeypatch, tmp_path):
    db_path = tmp_path / "legacy" / "clipforge.db"
    db = _reload_db(monkeypatch, tmp_path)
    monkeypatch.setenv("DB_URL", f"sqlite:///{db_path}")
    sys.modules.pop("db", None)
    db = importlib.import_module("db")

    assert db.database_dialect() == "sqlite"
    db.init_db()
    assert db_path.exists()


def test_database_url_summary_does_not_leak_credentials(monkeypatch, tmp_path):
    db = _reload_db(
        monkeypatch,
        tmp_path,
        database_url="postgresql+psycopg://dbuser:sensitive-value@example.internal:5432/clipforge?sslmode=require",
    )

    summary = db._safe_database_summary()

    assert summary["dialect"] == "postgresql"
    assert summary["host_configured"] is True
    assert summary["database"] == "clipforge"
    assert "sensitive-value" not in repr(summary)
    assert "dbuser" not in repr(summary)


def test_qmark_conversion_ignores_literals_and_comments(monkeypatch, tmp_path):
    db = _reload_db(monkeypatch, tmp_path)

    sql, params = db._convert_qmark_sql(
        "SELECT '?' AS literal, value FROM table_name -- ? in comment\nWHERE id = ? AND name = ?",
        (123, "wheel"),
    )

    assert "literal" in sql
    assert "-- ? in comment" in sql
    assert "id = :p0" in sql
    assert "name = :p1" in sql
    assert params == {"p0": 123, "p1": "wheel"}


def test_transaction_rolls_back_on_error(monkeypatch, tmp_path):
    db = _reload_db(monkeypatch, tmp_path)
    db.init_db()

    with pytest.raises(RuntimeError):
        with db.transaction() as conn:
            conn.execute(
                """
                INSERT INTO jobs (
                    project_name, product_name, product_brief, video_mode, ratio,
                    clip_duration, clip_count, resolution, youtube_title, privacy,
                    status, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    "rollback",
                    "widget",
                    "brief",
                    "single",
                    "16:9",
                    5,
                    1,
                    "720p",
                    "title",
                    "private",
                    "queued",
                    db.utc_now(),
                    db.utc_now(),
                ),
            )
            raise RuntimeError("force rollback")

    assert db.fetch_one("SELECT COUNT(*) AS count FROM jobs WHERE project_name = ?", ("rollback",))["count"] == 0


def test_v3_migrations_are_repeatable_on_sqlite(monkeypatch, tmp_path):
    db = _reload_db(monkeypatch, tmp_path)
    db.init_db()
    migrations = importlib.import_module("clipforge_v3.migrations")

    first = migrations.run_v3_migrations()
    second = migrations.run_v3_migrations()

    assert first
    assert second == []
    assert db.fetch_one("SELECT COUNT(*) AS count FROM schema_migrations")["count"] >= len(migrations.MIGRATIONS)


def test_postgresql_ddl_and_insert_ignore_are_compiled(monkeypatch, tmp_path):
    db = _reload_db(
        monkeypatch,
        tmp_path,
        database_url="postgresql+psycopg://dbuser:sensitive-value@example.internal/clipforge",
    )

    ddl = db._prepare_sql("CREATE TABLE example (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)")
    insert = db._prepare_sql("INSERT OR IGNORE INTO schema_migrations (name, applied_at) VALUES (:name, :applied_at)")

    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
    assert "AUTOINCREMENT" not in ddl
    assert insert.startswith("INSERT INTO schema_migrations")
    assert insert.endswith("ON CONFLICT DO NOTHING")


@pytest.mark.skipif(
    not os.getenv("POSTGRES_TEST_DATABASE_URL"),
    reason="Set POSTGRES_TEST_DATABASE_URL to run real PostgreSQL integration checks.",
)
def test_real_postgresql_empty_schema_and_repository_smoke(monkeypatch, tmp_path):
    database_url = os.environ["POSTGRES_TEST_DATABASE_URL"]
    db = _reload_db(monkeypatch, tmp_path, database_url=database_url)
    db.init_db()
    migrations = importlib.import_module("clipforge_v3.migrations")
    project_repository = importlib.import_module("clipforge_v3.repositories.project_repository")

    migrations.ensure_v3_schema()
    migrations.ensure_v3_schema()
    project_id = project_repository.create_project(
        {
            "project_name": "pg smoke",
            "product_name": "widget",
            "product_category": "tool",
            "target_market": "US",
            "target_audience": "DIY",
            "target_platform": "amazon",
            "aspect_ratio": "16:9",
            "total_duration": 5,
            "default_clip_duration": 5,
            "resolution": "720p",
            "language": "en",
        }
    )

    row = project_repository.get_project(project_id)
    assert row["project_name"] == "pg smoke"
